# Generated by Django 2.2 on 2020-02-14 18:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dojo_ninjas_app', '0002_ninjas_enrolled'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ninjas',
            name='enrolled',
        ),
        migrations.AddField(
            model_name='ninjas',
            name='dojos',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='enrolled', to='dojo_ninjas_app.dojos'),
            preserve_default=False,
        ),
    ]
