# Generated by Django 2.2 on 2020-02-14 18:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dojo_ninjas_app', '0003_auto_20200214_1847'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ninjas',
            name='dojos',
        ),
        migrations.AlterField(
            model_name='ninjas',
            name='dojo_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrolled', to='dojo_ninjas_app.dojos'),
        ),
    ]
